import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import NavigationBar from '../components/NavigationBar';
import BigPicture from '../components/BigPicture';
import Footer from '../components/Footer';
import ScrollerOne from '../components/ScrollerOne'; 
import ScrollerTwo from '../components/ScrollerTwo';
import Cam from '../components/Cam';
import ChamNgon from '../components/ChamNgon'; 

export default function Home() {
  return (
    <div>
    <NavigationBar />
    <BigPicture />
    <div className={styles.container}>
      <Head>
        <title>meo-dev-training-3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h2>THƯ TÌNH GỬI MỘT NGƯỜI</h2>
      <ScrollerOne />
      <h2 style = {{fontSize: "40px"}}>♫</h2>
      <ScrollerTwo />
      <h2>CẢM</h2>
      <Cam />
      <ChamNgon />
    </div>
    <Footer />
    </div>
  );
}
