import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>meo-dev-training-3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>THƯ TÌNH GỬI MỘT NGƯỜI</h2>
      <h2>CẢM</h2>
      <h2>CHÂM NGÔN TRỊNH</h2>
    </div>
  )
}
